### ISSUE TITLE
✨ Move token import from a pickle file import to a simple text file

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/update-web-metadata#21]
Currently in the[ parse_review_issues.py script here](https://github.com/pyOpenSci/update-web-metadata/blob/main/parse_review_issues.py#L18) the token is imported using a pickle file. however, it would be much simpler for users to just store the token string in a txt file and then add that txt file to the .gitignore to ensure the file is never added to .git history. 

Steps to complete this task

- [x] First update the code in parse_review_issues.py to import a txt file and populate the API_TOKEN variable rather than using a pickle. 
- [ ] Create a small helper function in the pyosmet src/ to import the parse the text file. 
- [x] Update the code in all three scripts as well to use the txt file rather than the pickle file
    - [x] [parse_review_issues.py](https://github.com/pyOpenSci/update-web-metadata/blob/main/parse_review_issues.py)
    - [ ] https://github.com/pyOpenSci/update-web-metadata/blob/main/parse-contributors.py
    - [x] https://github.com/pyOpenSci/update-web-metadata/blob/main/update_reviewers.py
- [x] Update the gitignore file to ensure the txt file is never populated into git history
- [x] Update README with instructions in creating the token and storing it for use.

**Comment by bbulpett** [comment]
I can work on this 🙂

**Comment by lwasser** [comment]
closed via #24 #24 many thanks again @bbulpett @paajake !! closing this issue as it is now COMPLETE!
