### ISSUE TITLE
Docs link missing in the website for some packages

### ISSUE THREAD

**Issue by juanis2112** [pyOpenSci/update-web-metadata#28]
At the Packages page on the website there are some docs link missing. (Probably cause they are not listed in the packages repo).

<img width="1280" alt="Screenshot 2023-05-13 at 1 43 05 PM" src="https://github.com/pyOpenSci/update-web-metadata/assets/18587879/909ddd17-c83e-4f0f-b350-4a0183047eeb">

I submitted a PR on the website to manually add these links: https://github.com/pyOpenSci/pyopensci.github.io/pull/177

**Comment by lwasser** [comment]
thank you for this @juanis2112 !!

**Comment by lwasser** [comment]
@all-contributors please add @juanis2112 for code,review

**Comment by lwasser** [comment]
i believe this has been fixed!! all packages on the website now have a docs link. thank you @juanis2112 for fixing this for us! closing this issue. feel free to reopen IF there are things not yet implemented!
